// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hioipmtmjsvilhbvicwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpb2lwbXRtanN2aWxoYnZpY3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjUzOTEsImV4cCI6MjA2NDk0MTM5MX0.xG2HfGFI4y4dmu4RWsbVoVHZ9gLU8g0CThe2t29m-LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);